### PR TITLE
fix SBUS input scaling for TX (using FrSky scaling)

### LINKED ISSUE #187: PPM scaling issue for SBUS input
@mikeller,
I just revisited a setup I have that takes SBUS input from an FrSky receiver (x8r), feeds it into an olrs TX, and outputs PPM on the RX side. The scaling appears to be broken, as I'm getting rollover on the lower-end of the stick range...

example:
I setup PPM debugging on the RX side to output the raw PPM values coming in over the air (prior to scaling on RX side). Moving a control stick to the bottom of its range causes the output to jump from a minimum value of '12' to '1023'. It appears there must be a problem with the scaling of the FrSky SBUS signal going into the TX, and it's causing the uint16 values to roll over.

Since you were the last one to work on the SBUS-PPM conversion stuff in TX.h, I figured I'd ask you first...

### PR DESCRIPTION
**Pull request by csurf**
- fixes SBUS scaling to match FrSky SBUS scaling, fixes #187
- code clean-up for serialPPM.h

### CODE REVIEW

File: openLRSng/TX.h [hunk 1]
```diff
@@ -696,7 +696,8 @@ static inline void processSpektrum(uint8_t c)
 
 static inline uint16_t SBUSToPpm(uint16_t input) {
   // Rescale [200, 1800] to [1000, 2000]
-  uint16_t value = (((input - 200) * 10) >> 4) + 1000;
+  // uint16_t value = (((input - 200) * 10) >> 4) + 1000;
```
Comment (mikeller) [inline openLRSng/TX.h]: Probably remove the comment.

Comment (csurf) [reply openLRSng/TX.h]: ok, so you're ok with this change? you mentioned having to fix the scaling on the other end as well?

Comment (mikeller) [reply openLRSng/TX.h]: Yes I am ok with it. If this is what's needed on the input side to create valid output, then that's what's needed.
